# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-15 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tweets_app', '0002_auto_20181114_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashtagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regex', models.CharField(max_length=25)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tweets_app.Tweet')),
            ],
        ),
    ]
