# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-15 05:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HashtagModel',
            new_name='Hashtag',
        ),
    ]
