# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-16 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='created_day',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
