# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-15 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets_app', '0002_auto_20181114_2132'),
        ('hashtags_app', '0002_auto_20181115_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='tweet',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='tweet',
            field=models.ManyToManyField(to='tweets_app.Tweet'),
        ),
    ]
