# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-16 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags_app', '0002_hashtag_created_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashtag',
            name='created_day',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
