# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-11-15 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags_app', '0003_auto_20181115_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='tweet',
        ),
    ]
